---
title: "Stat613 hw7"
author: "Cihui Yang"
date: "2021/3/26"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rvest)
library(dplyr)
library(tidyverse)
library(repurrrsive)

#1
Link <- "https://www.imdb.com/list/ls091520106/"
page = read_html(Link)
Title = page%>% html_nodes(".lister-item-header a")%>%
  html_text()
Title

Link <- "https://www.imdb.com/list/ls091520106/"
page = read_html(Link)
Ratings = page%>% html_nodes(".ipl-rating-star.small .ipl-rating-star__rating")%>%
  html_text()
Ratings

Link <- "https://www.imdb.com/list/ls091520106/"
page = read_html(Link)
Runtime = page%>% html_nodes(".text-muted .runtime")%>%
  html_text()
Runtime

movies = data.frame(Title, Ratings, Runtime)
movies

#2
#A nested list is a list that in another list. The example of nested list could be a= list(1,2,3, b = list (2,3,4)) List b is nested in List a.

#b
gh_repos
#This give the basic information about the github repos. The dataone component for each of the 6 GitHub users and each component is, in turn, a list with info on the user

#c
repos <- tibble(repo = gh_repos)
repos
#When run the data, all the data arrange into the lists. We can see there are 6 observations in the repo and each observation is a list. 

#d
listviewer::jsonedit(gh_repos)
#This time the elements of user are a list of repositories that belong to that user. We have a nested List configuration is to show each information belog to different users. If we think it in a simple way, ghrepos=list(a=list(...), b=list(...), c=list(...), d=list(...), e=list(...),f=list(...)). Inside each list of users, there are 30 lists, and 68 rows in each list. 

#e
tibble(repo = gh_repos) %>% 
  unnest_auto(repo) %>% 
  unnest_auto(repo)

```

